apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-receiver-1-0-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/data-receiver-1-0
  persistentVolumeReclaimPolicy: Retain
