apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-receiver-1-0
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
