apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storegateway
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
