---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: production
  namespace: monitoring
spec:
  image: quay.io/prometheus/prometheus:v2.49.1
  version: v2.49.1
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      prometheus: main
  podMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: devops-by-example

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 2Gi
  replicas: 1
  logLevel: info
  logFormat: logfmt
  retention: 6h
  scrapeInterval: 15s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: false
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        selector:
          matchLabels:
            app: prometheus
        volumeName: prometheus-pv
  remoteWrite:
    - url: http://10.0.0.230:10908/api/v1/receive
      queueConfig:
        maxSamplesPerSend: 1000
        maxShards: 200
        capacity: 2500
