apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/prometheus
  storageClassName: standard
  claimRef:
    namespace: monitoring
    name: prometheus-production-db-prometheus-production-0
