---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: objstore
stringData:
  objstore.yml: |-
    type: S3
    config:
      bucket: test
      endpoint: "10.96.26.199:9000"
      insecure: true
      access_key: "24w5MJQj4R4qe9Qh"
      secret_key: "bOThRh09iWRbxiNN9QuVihxTc3WKQRrU"
