apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: compactor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
