---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: objstore
stringData:
  objstore.yml: |-
    type: S3
    config:
      bucket: test
      endpoint: "10.109.237.85:9000"
      insecure: true
      access_key: "cukWieXcoWVXBoS1"
      secret_key: "5BhFkXpZVYnwCt0Hg6rFpvsi3BSOLb1c"
