apiVersion: v1
kind: PersistentVolume
metadata:
  name: storegateway-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/storegateway
  persistentVolumeReclaimPolicy: Retain
